# Generated by Django 3.1.5 on 2021-01-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address1',
            new_name='Address_Line_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Address2',
            new_name='Address_Line_2',
        ),
    ]
